name: esg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - requests
  - beautifulsoup4
  - urllib3
  - ipykernel
  - pip
  - selenium
  - pandas
  - numpy
  - transformers
  - huggingface_hub
  - tokenizers
  - sentencepiece
  - pytorch
  - jupyter
  - ipywidgets
  - nltk
  - python-dotenv
  - pip:
      - python-dotenv
      - accelerate
      - bitsandbytes